[package]
name = "networkless"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
fs2 = "0.4.3"
futures = "0.3.31"
log = "0.4.27"
simplelog = "0.12.2"
tokio = { version = "1.45.0", features = ["rt", "macros"] }
